name: Gitlab Mirror

on:
  push:
    branches:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: mirror-repository
      uses: yesolutions/mirror-action@master
      with:
        REMOTE: "https://gitlab.com/whoamikyo/thotsbay-bot.git"
        GIT_USERNAME: whoamikyo
        GIT_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        DEBUG: "true"