name: Gitlab Mirror

on:
  push:
    branches:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: mirror-repository
      uses: spyoungtech/mirror-action@v0.5.0
      with:
        REMOTE: git@gitlab.com:whoamikyo/thotsbay-bot.git
        GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
        GIT_SSH_KNOWN_HOSTS: ${{ secrets.GIT_SSH_KNOWN_HOSTS }}
        # GIT_SSH_NO_VERIFY_HOST: "true"
        DEBUG: "true"