name: Gitlab mirroring

on: 
  push:
    branches:
    - '**'
  workflow_dispatch:
    inputs:
      force:
        description: "Enter 'force' if you want to force a refresh"
        required: false
        default: ""

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitlab.com:whoamikyo/thotsbay-bot.git
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
