name: Run main

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:
    inputs:
      force:
        description: "Enter 'force' if you want to force a refresh"
        required: false
        default: ""
env:
  RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
  THOTSBAY_USER: ${{ secrets.THOTSBAY_USER }}
  THOTSBAY_PW: ${{ secrets.THOTSBAY_PW }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  ID_CONFIG: ${{ secrets.ID_CONFIG }}
  CONFIG: ${{ secrets.CONFIG }}
  IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
  CDN: ${{ secrets.CDN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  REFERER: ${{ secrets.REFERER }}
  LATEST_POST: ${{ secrets.LATEST_POST }}
  CONFIG_BACKUP: ${{ secrets.CONFIG_BACKUP }}
  ID_CONFIG_BACKUP: ${{ secrets.ID_CONFIG_BACKUP }}
  API_KEY: ${{ secrets.API_KEY }}
  URL_BASE: ${{ secrets.URL_BASE }}
  ENABLE_TASK: ${{ secrets.ENABLE_TASK }}
  CYBERDROP_TOKEN: ${{ secrets.CYBERDROP_TOKEN }}
  ID_CONFIG_TESTE: ${{ secrets.ID_CONFIG_TESTE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Checkout repo
      - uses: actions/checkout@v2
      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.10
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          poetry install --no-interaction --no-root
      - name: Install library
        run: poetry install --no-interaction
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      - name: Run main.py
        run: |
          source .venv/bin/activate
          python main.py
      - name: 🚀 Deploy changes
        run: |
          # set git author
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Auto-update"
          # finally push
          git push